### ISSUE TITLE
RuntimeError: CUDA error: invalid argument

### ISSUE THREAD

**Issue by fradino** [G-U-N/Gen-L-Video#3]
![image](https://github.com/G-U-N/Gen-L-Video/assets/31378961/0e52071e-9778-4dc9-945b-490f53e04e8d)
![image](https://github.com/G-U-N/Gen-L-Video/assets/31378961/2e7db9d9-9ac7-4532-b06b-e24b385fc2dd)
I try to run "accelerate launch one-shot-tuning.py --control=pose", the backward process is interrupted. How can I fix it? Thank you.

**Comment by G-U-N** [comment]
Hi, this error might be (but not definitely) caused by the GPU memory overflow. The default batch size in the hike.yaml file is set to 3, which needs around 30 GB of memory for tuning. If your GPUs have smaller memory, you can try reducing the batch size slightly in the hike.yaml file. This should help with the memory issue. Let me know if you need further assistance!

**Comment by fradino** [comment]
I fixed by change the torch version. Thank you for your response.

**Comment by G-U-N** [comment]
Could you tell me which version you just changed into? That might help me to inspect the potential problem in my `requirements.yaml`

**Comment by fradino** [comment]
![image](https://github.com/G-U-N/Gen-L-Video/assets/31378961/40cec692-f9c3-469e-b4e4-2c8584397239)
I followed this, but my cuda version is 11.7.

**Comment by G-U-N** [comment]
Thanks a lot.

**Comment by winshot-thu** [comment]
Hello,

I have been able to reproduce the issue you're encountering. The good news is that it can be resolved by compiling xformers from the source code. The method for setting up the new environment has been updated in the readme file. I have been tested, you can choose either cudatoolkit 11.7 or 11.6, both of them will work properly.

Let me know if there's anything else I can help you with.

Best regards.
